### ISSUE TITLE
install.py

### ISSUE THREAD

**Issue by ghost** [RoliSoft/WSL-Distribution-Switcher#73]
Not sure why it's failing to pobe_wsl ?

```
:~/WSL-Distribution-Switcher$ sudo python3 install.py rootfs_kalilinux_kali-linux-docker_latest.tar.gz
[*] Probing the Linux subsystem...
Traceback (most recent call last):
  File "install.py", line 48, in <module>
    basedir, lxpath = probe_wsl()
  File "/home/jan/WSL-Distribution-Switcher/utils.py", line 185, in probe_wsl
    basedir = os.path.join(os.getenv('LocalAppData'), 'lxss')
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by Dr-Chaos** [comment]
Because you use the script from your Subsystem !
You must use install.py from Windows (ex PowerShell)

**Comment by ghost** [comment]
Ohh right thanks.
