### ISSUE TITLE
`python install.py rootfs_kalilinux_kali-linux-docker_latest.tar.gz` with python 3.7

### ISSUE THREAD

**Issue by NandoPrates** [RoliSoft/WSL-Distribution-Switcher#86]
[*] Probing the Linux subsystem...
[*] Default user is root at /root.
[*] Reading /etc/{passwd,shadow,group,gshadow} entries for root...
[*] Beginning extraction...
[!] Failed to extract usr/share/doc/vim-tiny: [Errno 13] Permission 
denied: 'C:\\Users\\nando\\AppData\\Local\\lxss\\root\\rootfs-temp/usr/share/doc/vim-tiny'
[*] Backing up current rootfs to rootfs_ubuntu_xenial...
[*] Switching to new rootfs...
[*] Writing entries of root to /etc/{passwd,shadow,group,gshadow}...
PS C:\WSL-Distribution-Switcher>

**Comment by Lebensdesigner** [comment]
Same problem

**Comment by snowwolf109** [comment]
Same problem, do you find the solution for this? please advise

**Comment by GaryGMg** [comment]
I get an error from the installer.py:
python install.py rootfs_kalilinux_kali-linux-docker_latest.tar.gz

Traceback (most recent call last):
  File "install.py", line 15, in <module>
    from utils import *
  File "/root/WSL-Distribution-Switcher/utils.py", line 87
    def create_certifi_context(purpose = ssl.Purpose.SERVER_AUTH, *, cafile = None, capath = None, cadata = None):
                                                                   ^
SyntaxError: invalid syntax

Would someone know the correct syntax? Python isn't my strong suit yet.
